package com.stacs.cs5031.p3.client.gui.helper_classes;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;

/**
 * Code Generated by GUI Builder, "Window Builder for JavaFx/Swing" extension in vscode
 */
public class OnClickEventHelper {

    public static void setOnClickColor(JButton button, Color pressedColor, Color originalColor) {
    button.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                button.setContentAreaFilled(false);
                button.setBackground(pressedColor);
                button.setOpaque(true);
                button.repaint();
                System.out.println("Button Clicked");
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                button.setBackground(originalColor);
                button.repaint();
            }
        });
    }

}