
package com.stacs.cs5031.p3.client.gui.organiser;

import javax.swing.*;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;

import com.stacs.cs5031.p3.client.gui.helper_classes.CustomFontLoader;
import com.stacs.cs5031.p3.client.gui.helper_classes.OnClickEventHelper;
import com.stacs.cs5031.p3.client.gui.helper_classes.RoundedBorder;
import com.stacs.cs5031.p3.server.dto.UserDto;

/**
 * This class is responsible for creating the main page of the organiser.
 * Part of this code (i.e basic element layout code) was generated by GUI Builder, "Window Builder for
 * JavaFx/Swing" extension in vscode.
 */
public class OrganiserHomePage {


  /**
   * This is the constructor of the OrganiserHomePage class.
   * @param user - the user details
   */
  public OrganiserHomePage(UserDto  user) {

    createPage(user);
   
  }

  /**
   * This method is responsible  for creating the main page of the organiser.
   * @param user - the user details
   */
  public static void createPage( UserDto user) {
    JFrame frame = new JFrame("Organiser Home");
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setSize(896, 483);

    frame.setLocationRelativeTo(null);

    JPanel panel = new JPanel();
    panel.setLayout(null);
    panel.setBackground(Color.decode("#f4c064"));
    PageElements pageEl = new PageElements( user, panel, frame);
    pageEl.addAllElements();

    frame.add(panel);
    frame.setVisible(true);

  }

  

    /**
   * This class is responsible for creating the elements of the create booking
   * page.
   * It contains methods to create and add the elements to the panel.
   */
  public static class PageElements {
    private JPanel panel; // The panel to which the elements will be added
    private JFrame frame; // The frame to which the panel will be added
    private UserDto user; // The user details

    /**
     * This is the constructor of the PageElements class.
     * 
     * @param panel       - the panel to which the elements will be added
     * @param frame       - the frame to which the panel will be added
     * @param user       - the user details
     */
    public PageElements(UserDto user, JPanel panel, JFrame frame) {
      this.panel = panel;
      this.frame = frame;
      this.user = user;
      // getRooms();
    }

    /**
     * This button is responsible for adding all elements to the page.
     */
    public void addAllElements() {
      addViewBookingsButton();
      addCreateBookingButton();
      addOrganiserHomeLbl();
    }

    /**
     * This method is responsible adding the view booking button to the screen.
     * 
     */
    private void addViewBookingsButton() {

      JButton viewBookingsBtn = new JButton("View Bookings");
      viewBookingsBtn.setBounds(280, 267, 314, 40);
      viewBookingsBtn.setBackground(Color.decode("#bca8e4"));
      viewBookingsBtn.setForeground(Color.decode("#000"));
      viewBookingsBtn.setFont(CustomFontLoader.loadFont("./resources/fonts/Lexend.ttf", 14));
      viewBookingsBtn.setBorder(new RoundedBorder(4, Color.decode("#3d364a"), 1));
      viewBookingsBtn.setFocusPainted(false);
      OnClickEventHelper.setOnClickColor(viewBookingsBtn, Color.decode("#7c6f97"), Color.decode("#bca8e4"));
      panel.add(viewBookingsBtn);
      viewBookingsBtn.addActionListener(e -> {
        new MyBookingsPage(user).setVisible(true);
        frame.dispose();
      });

    }

    /**
     * This method is responsible for adding the create booking button to the screen.
     */
    private void addCreateBookingButton() {

      JButton createBookingBtn = new JButton("Create New Booking");
      createBookingBtn.setBounds(282, 176, 315, 40);
      createBookingBtn.setBackground(Color.decode("#bca8e4"));
      createBookingBtn.setForeground(Color.decode("#000"));
      createBookingBtn.setFont(CustomFontLoader.loadFont("./resources/fonts/Lexend.ttf", 14));
      createBookingBtn.setBorder(new RoundedBorder(4, Color.decode("#3d364a"), 1));
      createBookingBtn.setFocusPainted(false);
      OnClickEventHelper.setOnClickColor(createBookingBtn, Color.decode("#7c6f97"), Color.decode("#bca8e4"));

      createBookingBtn.addActionListener(e -> {
        new CreateBookingPage(user);
        frame.dispose();
      });
      panel.add(createBookingBtn);

    }

    /**
     * This method is used to add the Organiser Home Label at the top of the screen.
     */
    private void addOrganiserHomeLbl() {
      JLabel element3 = new JLabel("Organiser Home");
      element3.setBounds(275, 65, 401, 78);
      element3.setFont(CustomFontLoader.loadFont("./resources/fonts/Lexend.ttf", 40));
      element3.setForeground(Color.decode("#000"));
      panel.add(element3);
    }
  }

}